name: Newsletter and Podcasts Dump

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: 1 - Executar Crawler (Articles)
        run: python scripts/main.py --target articles

      - name: 2 - Executar Crawler (Podcasts)
        run: python scripts/main.py --target podcasts

      - name: 3 - Verificar arquivos para o Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"          
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: update data $(date +'%Y-%m-%d %H:%M')"
            git push
          else
            echo "Nenhuma nova informação encontrada no blog."
          fi